### ISSUE TITLE
Set up SSH tunnel from Groundstation to Satellite

### ISSUE THREAD

**Issue by aDotInTheVoid** [gpuctl/gpuctl#18]
For securing traffic containing GPU usage data/control commands.

Overview is as follows. We don't want to need external certificates/HTTPS in order to secure traffic (so the whole service can be run on a firewalled network). Instead, we'll piggy-back on the existing ssh infra in order to communicate, using SSH tunneling. We'll make a tunnel to/from the groundstation and satellite (so all communications on localhost to a particular port connect to a particular port on the other side), and then use http over that tunnel*.

*HTTP over ssh from satellite to groundstation is fine, the data is in plaintext on the satellite machine itself, but anyone with access to the machine can already get access to the same data as by running the nvidia command anyway. However going back the other way, aren't we going to have to have a server on localhost that any user on the machine can access to control the machine - do we instead want to just use a bash script over SSH that rely just on the fact the user the satellite binary is run under has reboot privileges??

https://pkg.go.dev/golang.org/x/crypto/ssh
https://eli.thegreenplace.net/2022/ssh-port-forwarding-with-go/

- [ ] Create function for making/closing a ssh tunnel with Go (abstract to a module in `internal/`)
- [ ] Rewrite data send functions to make requests through this ssh tunnel
- [ ] Add HTTP endpoints to the satellite for receiving control commands (maybe? see *)

**Comment by danielg0** [comment]
This issue is now done to the extent needed for the project.

- Serving over HTTPS was easier than it seemed, we were able to use Caddy/Let's Encrypt with DNS challenges to get certificates without exposing the service to the wider net (#99).
- SSH is used to onboard/reboot new machines, copying across the satellite binary then running it (#101), as well as when removing it from the database (#262)
- We don't send any other control commands to the satellites, reboot is done through giving a command for the user to run (#188)
