### ISSUE TITLE
Fix downsampling crashes

### ISSUE THREAD

**Issue by sirjacobofglais** [gpuctl/gpuctl#219]

**Comment by aDotInTheVoid** [comment]
Any logs of this happening?

**Comment by NathanielB123** [comment]
> Any logs of this happening?

https://discord.com/channels/1193956842368417863/1193956843333103758/1210970497542529124
https://discord.com/channels/1193956842368417863/1193956843333103758/1211469576089374832

**Comment by NathanielB123** [comment]
I think it would also be ideal to sanity check the results of downsampling - i.e. just run for a while and see if the values are in reasonable ranges, because right now I don't think we have any front-end behaviour that allows us to see older/downsampled data.

**Comment by danielg0** [comment]
> I think it would also be ideal to sanity check the results of downsampling - i.e. just run for a while and see if the values are in reasonable ranges, because right now I don't think we have any front-end behaviour that allows us to see older/downsampled data.

Yes, I agree, I don't know if this is worth properly fixing til we have long term data stats coming out of the db to compare with in unit tests. I'd suggest we just make it so errors are logged rather than returned from downsample, then fix "properly" once we have those long term data stats coming out of the db
